//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="uidAbfrageServiceBinding", Namespace="https://finanzonline.bmf.gv.at/fon/ws/uidAbfrage")]
public partial class uidAbfrageService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback uidAbfrageOperationCompleted;
    
    /// <remarks/>
    public uidAbfrageService() {
        this.Url = "https://finanzonline.bmf.gv.at/fon/ws/uidAbfrage/";
    }
    
    /// <remarks/>
    public event uidAbfrageCompletedEventHandler uidAbfrageCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("uidAbfrage", RequestElementName="uidAbfrageServiceRequest", RequestNamespace="https://finanzonline.bmf.gv.at/fon/ws/uidAbfrage", ResponseElementName="uidAbfrageServiceResponse", ResponseNamespace="https://finanzonline.bmf.gv.at/fon/ws/uidAbfrage", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("rc")]
    public int uidAbfrage(string tid, string benid, string id, string uid_tn, string uid, uidAbfrageServiceRequestStufe stufe, out string msg, out string name, out string adrz1, out string adrz2, out string adrz3, out string adrz4, out string adrz5, out string adrz6) {
        object[] results = this.Invoke("uidAbfrage", new object[] {
                    tid,
                    benid,
                    id,
                    uid_tn,
                    uid,
                    stufe});
        msg = ((string)(results[1]));
        name = ((string)(results[2]));
        adrz1 = ((string)(results[3]));
        adrz2 = ((string)(results[4]));
        adrz3 = ((string)(results[5]));
        adrz4 = ((string)(results[6]));
        adrz5 = ((string)(results[7]));
        adrz6 = ((string)(results[8]));
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginuidAbfrage(string tid, string benid, string id, string uid_tn, string uid, uidAbfrageServiceRequestStufe stufe, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("uidAbfrage", new object[] {
                    tid,
                    benid,
                    id,
                    uid_tn,
                    uid,
                    stufe}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EnduidAbfrage(System.IAsyncResult asyncResult, out string msg, out string name, out string adrz1, out string adrz2, out string adrz3, out string adrz4, out string adrz5, out string adrz6) {
        object[] results = this.EndInvoke(asyncResult);
        msg = ((string)(results[1]));
        name = ((string)(results[2]));
        adrz1 = ((string)(results[3]));
        adrz2 = ((string)(results[4]));
        adrz3 = ((string)(results[5]));
        adrz4 = ((string)(results[6]));
        adrz5 = ((string)(results[7]));
        adrz6 = ((string)(results[8]));
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void uidAbfrageAsync(string tid, string benid, string id, string uid_tn, string uid, uidAbfrageServiceRequestStufe stufe) {
        this.uidAbfrageAsync(tid, benid, id, uid_tn, uid, stufe, null);
    }
    
    /// <remarks/>
    public void uidAbfrageAsync(string tid, string benid, string id, string uid_tn, string uid, uidAbfrageServiceRequestStufe stufe, object userState) {
        if ((this.uidAbfrageOperationCompleted == null)) {
            this.uidAbfrageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuidAbfrageOperationCompleted);
        }
        this.InvokeAsync("uidAbfrage", new object[] {
                    tid,
                    benid,
                    id,
                    uid_tn,
                    uid,
                    stufe}, this.uidAbfrageOperationCompleted, userState);
    }
    
    private void OnuidAbfrageOperationCompleted(object arg) {
        if ((this.uidAbfrageCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.uidAbfrageCompleted(this, new uidAbfrageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://finanzonline.bmf.gv.at/fon/ws/uidAbfrage")]
public enum uidAbfrageServiceRequestStufe {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void uidAbfrageCompletedEventHandler(object sender, uidAbfrageCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class uidAbfrageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal uidAbfrageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
    
    /// <remarks/>
    public string msg {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[1]));
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[2]));
        }
    }
    
    /// <remarks/>
    public string adrz1 {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[3]));
        }
    }
    
    /// <remarks/>
    public string adrz2 {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[4]));
        }
    }
    
    /// <remarks/>
    public string adrz3 {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[5]));
        }
    }
    
    /// <remarks/>
    public string adrz4 {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[6]));
        }
    }
    
    /// <remarks/>
    public string adrz5 {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[7]));
        }
    }
    
    /// <remarks/>
    public string adrz6 {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[8]));
        }
    }
}
